### ISSUE TITLE
Compile time error related to "select" constant in Sort enum.

### ISSUE THREAD

**Issue by AramayisO** [AlgorithmsProject115/CSCI115Project#7]
After the last merge, I am unable to compile the code. There seems to be an issue with using select as one of the constants in the Sort enum. Below is the compiler error:

aramayis@aramayis:~/Projects/CSCI115Project/CSCI 115 Project/CSCI 115 Project$ g++ --std=c++11 -o main main.cpp
main.cpp:110:20: error: ‘select’ redeclared as different kind of symbol
 enum Sort {insert, select, bubble, merge, quick, heap};
                    ^~~~~~
In file included from /usr/include/x86_64-linux-gnu/sys/types.h:196,
                 from /usr/include/stdlib.h:394,
                 from /usr/include/c++/8/cstdlib:75,
                 from /usr/include/c++/8/ext/string_conversions.h:41,
                 from /usr/include/c++/8/bits/basic_string.h:6391,
                 from /usr/include/c++/8/string:52,
                 from /usr/include/c++/8/stdexcept:39,
                 from /usr/include/c++/8/array:39,
                 from /usr/include/c++/8/tuple:39,
                 from /usr/include/c++/8/bits/hashtable_policy.h:34,
                 from /usr/include/c++/8/bits/hashtable.h:35,
                 from /usr/include/c++/8/unordered_map:46,
                 from main.cpp:2:
/usr/include/x86_64-linux-gnu/sys/select.h:101:12: note: previous declaration ‘int select(int, fd_set*, fd_set*, fd_set*, timeval*)’
 extern int select (int __nfds, fd_set *__restrict __readfds,
            ^~~~~~
main.cpp: In function ‘int main()’:
main.cpp:223:9: error: invalid conversion from ‘int (*)(int, fd_set*, fd_set*, fd_set*, timeval*)’ to ‘int’ [-fpermissive]
    case select:
         ^~~~~~
main.cpp:223:9: error: ‘(int)select’ is not a constant expression
main.cpp:223:9: error: conversion from pointer type ‘int (*)(int, fd_set*, fd_set*, fd_set*, timeval*)’ to arithmetic type ‘int’ in a constant expression

**Comment by ghost** [comment]
Fixed in Pull Request #8
